# Changes here will be overwritten by Copier
_commit: v0.18.0
_src_path: gh:sarthakjariwala/django-vite-inertia
allauth: false
database: postgresql
docker_dev: false
docker_prod: true
frontend: react
project_name: immob
starter_kit: true
tailwind_css: true

