# Generated by Django 5.2.7 on 2025-11-06 23:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('ACCESS_DENIED', 'Access denied')], db_index=True, max_length=20, verbose_name='Action')),
                ('entity_type', models.CharField(db_index=True, max_length=100, verbose_name='Entity type')),
                ('entity_id', models.UUIDField(db_index=True, verbose_name='Entity ID')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Old values')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='New values')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('action_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'immob_audit_logs',
                'ordering': ['-action_date'],
                'indexes': [models.Index(fields=['user', 'action_date'], name='immob_audit_user_id_d72a20_idx'), models.Index(fields=['entity_type', 'entity_id'], name='immob_audit_entity__9362ff_idx'), models.Index(fields=['action', 'action_date'], name='immob_audit_action_2fd493_idx'), models.Index(fields=['action_date'], name='immob_audit_action__eca163_idx')],
            },
        ),
    ]
