# Generated by Django 5.2.7 on 2025-11-06 23:10

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('holdings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('contract_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Contract number')),
                ('start_date', models.DateField(db_index=True, verbose_name='Start date')),
                ('end_date', models.DateField(db_index=True, verbose_name='End date')),
                ('signature_date', models.DateTimeField(blank=True, null=True, verbose_name='Signature date')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monthly rent')),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Security deposit')),
                ('charges', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Charges')),
                ('payment_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], default='MONTHLY', max_length=20, verbose_name='Payment frequency')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('terms', models.TextField(blank=True, null=True, verbose_name='Contract terms')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_contracts', to='holdings.property')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contracts', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'immob_contracts',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount')),
                ('due_date', models.DateField(db_index=True, verbose_name='Due date')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('LATE', 'Late'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank transfer'), ('CHECK', 'Check'), ('CARD', 'Card')], max_length=20, null=True, verbose_name='Payment method')),
                ('reference_number', models.CharField(max_length=100, unique=True, verbose_name='Reference number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_payments', to='finance.contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'immob_payments',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Invoice number')),
                ('issue_date', models.DateField(db_index=True, verbose_name='Issue date')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total amount')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Invoice PDF')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_invoices', to='finance.payment')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'immob_invoices',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last name')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('id_number', models.CharField(help_text='Should be encrypted at application level', max_length=255, unique=True, verbose_name='ID number (encrypted)')),
                ('address', models.TextField(verbose_name='Address')),
                ('emergency_contact_name', models.CharField(max_length=200, verbose_name='Emergency contact name')),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name='Emergency contact phone')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'immob_tenants',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_contracts', to='finance.tenant'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['contract', 'due_date'], name='immob_payme_contrac_2ebc5f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'due_date'], name='immob_payme_status_07577d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference_number'], name='immob_payme_referen_496ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['payment', 'issue_date'], name='immob_invoi_payment_4a3e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'issue_date'], name='immob_invoi_status_72ffc3_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='immob_invoi_invoice_f70bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['email'], name='immob_tenan_email_1f1a97_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['last_name', 'first_name'], name='immob_tenan_last_na_5b2a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['property', 'status'], name='immob_contr_propert_dd7177_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'status'], name='immob_contr_tenant__f9c859_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date', 'end_date'], name='immob_contr_start_d_5b3a28_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', 'end_date'], name='immob_contr_status_013097_idx'),
        ),
    ]
