# Generated by Django 5.2.7 on 2025-11-06 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('holdings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpropertypermission',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='holdings.building'),
        ),
        migrations.AddField(
            model_name='userpropertypermission',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpropertypermission',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='holdings.property'),
        ),
        migrations.AddField(
            model_name='userpropertypermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspace',
            name='admin',
            field=models.OneToOneField(limit_choices_to={'role': 'OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_workspace', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='immobuser',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.workspace'),
        ),
        migrations.AddIndex(
            model_name='userpropertypermission',
            index=models.Index(fields=['user', 'expires_at'], name='immob_user__user_id_dd1959_idx'),
        ),
        migrations.AddIndex(
            model_name='userpropertypermission',
            index=models.Index(fields=['building', 'user'], name='immob_user__buildin_45c01b_idx'),
        ),
        migrations.AddIndex(
            model_name='userpropertypermission',
            index=models.Index(fields=['property', 'user'], name='immob_user__propert_959898_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpropertypermission',
            unique_together={('user', 'building', 'property')},
        ),
        migrations.AddIndex(
            model_name='immobuser',
            index=models.Index(fields=['email', 'is_active'], name='immob_users_email_6ef23e_idx'),
        ),
        migrations.AddIndex(
            model_name='immobuser',
            index=models.Index(fields=['role', 'is_deleted'], name='immob_users_role_75072e_idx'),
        ),
    ]
