# Generated by Django 5.2.7 on 2025-11-06 23:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('holdings', '0002_alter_building_floor_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBuildingPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='holdings.building')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_building_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Building Permission',
                'verbose_name_plural': 'User Building Permissions',
                'db_table': 'immob_user_building_permissions',
            },
        ),
        migrations.DeleteModel(
            name='UserPropertyPermission',
        ),
        migrations.AddIndex(
            model_name='userbuildingpermission',
            index=models.Index(fields=['user', 'expires_at'], name='immob_user__user_id_3751b1_idx'),
        ),
        migrations.AddIndex(
            model_name='userbuildingpermission',
            index=models.Index(fields=['building', 'user'], name='immob_user__buildin_dd917d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbuildingpermission',
            unique_together={('user', 'building')},
        ),
    ]
