# Generated by Django 5.2.7 on 2025-11-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('holdings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbuildingpermission',
            name='permission_level_score',
            field=models.PositiveIntegerField(default=1, help_text='Score numerique du niveau de permission pour faciliter les requetes', verbose_name='Permission level score'),
        ),
        migrations.AlterField(
            model_name='userbuildingpermission',
            name='permission_level',
            field=models.CharField(choices=[('VIEW', 'View'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], default='VIEW', max_length=10, verbose_name='Permission level'),
        ),
        migrations.AddIndex(
            model_name='userbuildingpermission',
            index=models.Index(fields=['user', 'permission_level'], name='immob_user__user_id_53cd2e_idx'),
        ),
    ]
