# Generated by Django 5.2.7 on 2025-10-19 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userpropertypermission_owner'),
        ('holdings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpropertypermission',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='holdings.building'),
        ),
        migrations.AddField(
            model_name='userpropertypermission',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpropertypermission',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='holdings.property'),
        ),
        migrations.AddField(
            model_name='userpropertypermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userpropertypermission',
            index=models.Index(fields=['user', 'expires_at'], name='immob_user__user_id_dd1959_idx'),
        ),
        migrations.AddIndex(
            model_name='userpropertypermission',
            index=models.Index(fields=['building', 'user'], name='immob_user__buildin_45c01b_idx'),
        ),
        migrations.AddIndex(
            model_name='userpropertypermission',
            index=models.Index(fields=['property', 'user'], name='immob_user__propert_959898_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpropertypermission',
            unique_together={('user', 'building', 'property')},
        ),
    ]
