# Generated by Django 5.2.7 on 2025-11-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userbuildingpermission_delete_userpropertypermission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbuildingpermission',
            name='can_create',
        ),
        migrations.RemoveField(
            model_name='userbuildingpermission',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='userbuildingpermission',
            name='can_update',
        ),
        migrations.RemoveField(
            model_name='userbuildingpermission',
            name='can_view',
        ),
        migrations.AddField(
            model_name='userbuildingpermission',
            name='permission_level',
            field=models.CharField(choices=[('VIEW', 'View'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], default='VIEW', max_length=10),
        ),
    ]
