# Generated by Django 5.2.7 on 2025-10-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpropertypermission_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immobuser',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Failed login attempts'),
        ),
        migrations.AddField(
            model_name='immobuser',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last failed login'),
        ),
    ]
