# Generated by Django 5.2.7 on 2025-10-26 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_immobuser_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpropertypermission',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
