# Generated by Django 5.2.7 on 2025-11-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userpropertypermission_granted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobuser',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone number'),
        ),
    ]
