# Generated by Django 5.2.7 on 2025-11-06 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='floor_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of floors'),
        ),
    ]
